### ISSUE TITLE
Make build process more robust

### ISSUE THREAD

**Issue by opticyclic** [plantuml-stdlib/Azure-PlantUML#10]
The README in the scripts directory says:

     You also need to download the Microsoft Azure, Cloud and Enterprise Symbol / Icon Set and copy all files from Symbols\CnE_Cloud\SVG to source/official

The current file is [Microsoft_Cloud_AI_Azure_Service_Icon_Set_2019_05_08_2.zip](https://download.microsoft.com/download/1/7/1/171DA19A-5477-4F50-B354-4ABAF28502A6/Microsoft_Cloud_AI_Azure_Service_Icon_Set_2019_05_08_2.zip)

This no longer has the `Symbols\CnE_Cloud\SVG` directory.

If you extract the zip as is the build fails.

If you extract the zip using the flat option, most but not all of the files are found.

Some of the files that are in the `manual` directory are now also in the `official` directory.
e.g. `manual/Azure App Service - Web App (was Websites)` is `official/App Services`

This means that the build is not reproducible.

You need a way to ensure consistency.
A few different ways you could do this is:
* check in all the files from the official version you used with a reference to the version number
* put a direct link to the version of the official zip file used (assuming that Microsoft keeps archives)
* Mirror the zips in another repo and link to the git hash (to save repo space in this repo)

etc

**Comment by Potherca** [comment]
@opticyclic Would these issues be resolved by the (code) changes in https://github.com/plantuml-stdlib/Azure-PlantUML/pull/31 ?

If so, we could close this issue once the MR is merged.

**Comment by Potherca** [comment]
I am closing this issue, due to lack of response. I this still turns out to be an issue, it can always be reopened on request.
