### ISSUE TITLE
Azure App Configuration missing

### ISSUE THREAD

**Issue by Steven-Beasley** [plantuml-stdlib/Azure-PlantUML#18]
There doesn't seem to be resource icons, and associated puml file for Azure App Configuration.

**Comment by Potherca** [comment]
Closed in favor of #29

**Comment by Potherca** [comment]
@Steven-Beasley the main MR that is going to update all icons (both from the official ZIP and manually added ones) currently does not contain an icon for Azure App Configuration.

Could you share an URL to a page where such an icon is used so it can be added?
