### ISSUE TITLE
Update URL for Azure icons to latest

### ISSUE THREAD

**Issue by phatcher** [plantuml-stdlib/Azure-PlantUML#28]
The current set of icons is available [here](https://docs.microsoft.com/en-us/azure/architecture/icons/) rather than the one pointed to on the project's readme

**Comment by Potherca** [comment]
Hi! Thank you for taking the time to report this!

I'll update the URL. :+1:

**Comment by phatcher** [comment]
NP - Is is worthwhile listing all the icons used in the Azure Portal that for resource types that are not in the standard icon set, not sure if we should nudge MS to include them or just use them here.

Specifically, I'm trying to document some messaging stuff and this is not well represented overall - happy to help, but need a bit of guidance as to most appropriate route.

**Comment by Potherca** [comment]
I'll have a look at this as soon as my schedule clears up a bit. :+1:
