### ISSUE TITLE
FEATURE: Management Structures

### ISSUE THREAD

**Issue by willis7** [plantuml-stdlib/Azure-PlantUML#30]
It would be great if we could model the hierarchical constructs withing azure. Something like:

![](https://cloudacademy.com/wp-content/uploads/2019/07/scope-levels.png)

Unfortunately, I neither possess the time nor skills to offer any help on this one.

**Comment by phatcher** [comment]
@willis7 If you have a look at my [latest update](https://github.com/phatcher/Azure-PlantUML/blob/feature/iconupdate/AzureSymbols.md) you can see I've added Management Groups, Subscriptions and Resource Groups (plus a lot more) - have a look and see if there's anything else that's missing

**Comment by willis7** [comment]
This is fantastic. This update covers everything I was looking for. Apologies, for not digging deeper to find this. Great work.

**Comment by cveld** [comment]
@willis7 can you share an example how you would draw the very diagram you shared with plantuml?

**Comment by Potherca** [comment]
@cveld The answer to your question _kind-of_ depends on how you want to build your diagram.
Do you only want to use the Sprites provided by this project? Or do you want to use the Macros? Or do you want to create the diagrams (also) using PlantUML C4?

That said, a first attempt might look something like this:

```plantuml
@startuml

!include <azure/AzureCommon>
!include <azure/Compute/all>
!include <azure/Databases/AzureSqlDatabase>
!include <azure/Identity/AzureAppRegistration>
!include <azure/Management/all>
!include <azure/Networking/AzureVirtualNetwork>
!include <azure/Security/all>

skinparam {
    backgroundColor transparent
    defaultFontSize 24
    rectangleBackgroundColor white
}

rectangle {
    label "Management groups" as management_label
    label "<$AzureManagementGroups>" as managementGroup

    management_label -[hidden] managementGroup
}

rectangle {
    label "Subscriptions" as subscription_label
    label "<$AzureSubscription>" as subscription_1
    label "<$AzureSubscription>" as subscription_2
}

rectangle {
    label "Resource groups" as resourceGroup_label
    label "<$AzureResourceGroups>" as resourceGroup_1
    label "<$AzureResourceGroups>" as resourceGroup_2
    label "<$AzureResourceGroups>" as resourceGroup_3
}

rectangle {
    label "Resources" as resource_label

    together {
        label "<$AzureVirtualMachine{scale=0.5}>" as resource_1a
        label "<$AzureVirtualNetwork{scale=0.5}>" as resource_1b
        label "<$AzureAppRegistration{scale=0.5}>" as resource_1c

        resource_1a -[hidden] resource_1b
        resource_1b -[hidden] resource_1c
    }

    label "<$AzureSqlDatabase>" as resource_2
    label "<$AzureAutomation>" as resource_3
}

management_label -[hidden]- subscription_label
subscription_label -[hidden]- resourceGroup_label
resourceGroup_label -[hidden]- resource_label

managementGroup .. subscription_1
managementGroup .. subscription_2

subscription_1 .. resourceGroup_1
subscription_1 .. resourceGroup_2
subscription_2 .. resourceGroup_3

resourceGroup_1 .. resource_1b
resourceGroup_2 .. resource_2
resourceGroup_3 .. resource_3

@enduml
```

[![](https://www.plantuml.com/plantuml/svg/dPH1RnCn48Nl_XMcujgKRE1MeeOY48ToI2Gk2A69TzXOzTgBFLP5g_ntDiwIxiuwAMqEEJo_xtacuybL8F0KQoDUQQjCB55UmdtqUB7OVL-xkdPsFZfizIOINe0nuyEFGB26W66ViVfj_YbZxvSIBMdwixSkccQ9bGxaWNJktXkmK67TClchloBTEN-hRRKF_AOzHJ2TFFQlK4M_kpwbYT2I3NYevOEGxMSDwhRoBjhosXdd9NcmeJMWfNHUuY-8XZuvIojzZx9ucsIFYi1M1Zym_cwZ2SLMY8EZkyZ06eqyUsnFxh0cd4a8iZweFvElJro-Jdq-WfyJDsTWKaK2UPey_xxHPOds1_UVA7GLrq5vtUocj2yoz9IZPVQn-HYRFXyfJXIvnE2YLzZ_BNsdfGQFrhdiky8yGqvVH1KlecR_qUEmkwwnP2HN8MtGTnmluB0ZDw0ssk93K63m_Pl9k-ryc3c5V01RiXC1wtm0N_iJ2KeS8dfrzPvmxhAUbdMgvDmADXpstyLAoOro4SdLgGLcJXCyldZdkUrX4WDoxvXh766FWssxd4pODZxfA8GO4gs3xycJZcBeACQEcM2jfPJ-f5dYuBWGB6rmEXDNQCjOcxy0)](https://www.plantuml.com/plantuml/uml/dPH1RnCn48Nl_XMcujgKRE1MeeOY48ToI2Gk2A69TzXOzTgBFLP5g_ntDiwIxiuwAMqEEJo_xtacuybL8F0KQoDUQQjCB55UmdtqUB7OVL-xkdPsFZfizIOINe0nuyEFGB26W66ViVfj_YbZxvSIBMdwixSkccQ9bGxaWNJktXkmK67TClchloBTEN-hRRKF_AOzHJ2TFFQlK4M_kpwbYT2I3NYevOEGxMSDwhRoBjhosXdd9NcmeJMWfNHUuY-8XZuvIojzZx9ucsIFYi1M1Zym_cwZ2SLMY8EZkyZ06eqyUsnFxh0cd4a8iZweFvElJro-Jdq-WfyJDsTWKaK2UPey_xxHPOds1_UVA7GLrq5vtUocj2yoz9IZPVQn-HYRFXyfJXIvnE2YLzZ_BNsdfGQFrhdiky8yGqvVH1KlecR_qUEmkwwnP2HN8MtGTnmluB0ZDw0ssk93K63m_Pl9k-ryc3c5V01RiXC1wtm0N_iJ2KeS8dfrzPvmxhAUbdMgvDmADXpstyLAoOro4SdLgGLcJXCyldZdkUrX4WDoxvXh766FWssxd4pODZxfA8GO4gs3xycJZcBeACQEcM2jfPJ-f5dYuBWGB6rmEXDNQCjOcxy0)
