### ISSUE TITLE
Add icons still missing after recent update

### ISSUE THREAD

**Issue by Potherca** [plantuml-stdlib/Azure-PlantUML#34]
The recent update from #31 update (almost) all icons. Besides from some image corruption (being addressed in #32), it needs to be checked that none of the requested icon are missing.

From the overview of #29, the following icon _might_ be missing:

- [ ] Azure App Configuration
- [x] Azure Purview
- [ ] Generic "Internet" cloud that looks "azure-ish"

Also, the currently open MRs could also contain icons that are not in the current set:

- [ ] #26 
- [ ] #17

Both need to be verified, and either marked as complete or have a linked issue or MR that adds them.

_This issue is a follow-up to #29 and related MR(s)._

**Comment by asos-eugeneniemand** [comment]
I see a PowerBI Embedded but no Native PowerBI is this by design? Also Synapse and PurView will be handy

**Comment by Potherca** [comment]
@asos-eugeneniemand Purview icons will be added as part of #37

**Comment by travisnielsen** [comment]
Agree that it would be helpful to have an icon for (regular) Power BI. I could add it to #37 and use the same icon provided for Embedded.

**Comment by Potherca** [comment]
> I could add it to #37 and use the same icon provided for Embedded.

@travisnielsen If you could, that would be awesome! 👍

**Comment by travisnielsen** [comment]
Power BI icon added to the Analytics section. I also moved Power BI Embedded from the Databases section to Analytics.
