### ISSUE TITLE
Use the new Azure "Fluent" logo

### ISSUE THREAD

**Issue by roel4ez** [plantuml-stdlib/Azure-PlantUML#38]
I love this repo as it is a good and helpful resource to get icons for diagram easily and without hassle. Great work!

Azure has a new logo: https://azure.microsoft.com/en-in/blog/a-fluent-new-look-for-the-azure-icon/, svg can be found here: https://en.wikipedia.org/wiki/File:Microsoft_Azure.svg
![image](https://user-images.githubusercontent.com/1822123/151184345-c2c30c64-7f7e-41d7-8a93-342a9a6f8128.png)

It would be great if that one could be added to the list.

I'm happy to submit a PR, just not sure where it all has to be changed (png and svg are easy enough to find, but not sure if there are any sprites that need updating)

Thanks!

**Comment by travisnielsen** [comment]
Icon fixed in #37
