### ISSUE TITLE
table.md icons broken due to extra "dist" in path

### ISSUE THREAD

**Issue by smadep** [plantuml-stdlib/Azure-PlantUML#43]
https://github.com/plantuml-stdlib/Azure-PlantUML/blob/e38467c5c9c801fa3e5f49346b9d41f5cdd81413/scripts/lib/MarkdownTable.cs#L38

and second occurance below.

**Comment by Potherca** [comment]
Thank you for reporting this! Somehow I completely missed the GitHub notification for this issue :disappointed:

**Comment by travisnielsen** [comment]
**table.md** is written to the `dist` folder as part of sprite generation process. The contents of that file are used to replace the table in [AzureSymbols.md](https://github.com/plantuml-stdlib/Azure-PlantUML/blob/master/AzureSymbols.md) which is a directory level higher. Therefore, `dist` is required in the path and you can see icons load correctly on the Azure symbols page.

I don't believe we have this documented and I can add it to Release v2.2.

**Comment by Potherca** [comment]
Resolved by #44
